import { StyleSheet } from 'react-native';
import { useTheme } from '@/shared/context/ThemeContext';

export const useThemedStyles = () => {
  const { isDark } = useTheme();
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#111827',
    },
    flex_1: {
      flex: 1,
    },
    canvas: {
      flex: 1,
      backgroundColor: '#E9EBED',
      position: 'absolute',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%',
      width: '100%',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    permissionBox: {
      backgroundColor: '#1F2937',
      borderRadius: 20,
      padding: 40,
      alignItems: 'center',
      marginHorizontal: 20,
      borderWidth: 1,
      borderColor: '#374151',
    },
    permissionLoader: {
      marginBottom: 20,
    },
    permissionTitle: {
      color: '#F9FAFB',
      fontSize: 18,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 8,
    },
    permissionSubtitle: {
      color: '#9CA3AF',
      fontSize: 14,
      textAlign: 'center',
    },
    hiddenCamera: {
      position: 'absolute',
      opacity: 0,
      width: 1,
      height: 1,
    },
    headerContainer: {
      width: '95%',
      height: '8%',
      marginHorizontal: 'auto',
      marginTop: 16,
    },
    headerBox: {
      width: '100%',
      height: '100%',
      borderWidth: 1,
      flex: 1,
      borderColor: '#374151',
    },
    headerTitle: {
      color: '#F9FAFB',
      fontSize: 24,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: 8,
    },
    stateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: [
        {
          translateX: '-50%',
        },
        {
          translateY: '-50%',
        },
      ],
      gap: 10,
    },
    stateDot: {
      width: 12,
      height: 12,
      borderRadius: 12,
      marginRight: 8,
      elevation: 12,
    },
    stateText: {
      color: '#9CA3AF',
      fontSize: 16,
      fontWeight: '500',
      textAlign: 'center',
    },
    counterContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    counterBox: {
      backgroundColor: '#1F2937',
      borderRadius: 32,
      padding: 48,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#374151',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 10,
      minWidth: '70%',
      minHeight: '40%',
      alignContent: 'center',
      justifyContent: 'center',
    },
    counterLabel: {
      color: '#9CA3AF',
      fontSize: 18,
      fontWeight: '500',
      marginBottom: 12,
    },
    counterValue: {
      color: '#F9FAFB',
      fontSize: 80,
      fontWeight: '800',
      lineHeight: 80,
    },
    statusRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      marginBottom: 20,
    },
    buttonBoxContianer: {
      top: '50%',
      left: '50%',
      // width: '100%',
      transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
    },
    buttonBox: {
      // backgroundColor: '#1F2937',
      borderRadius: 20,
      width: '100%',
      padding: 2,
      // borderColor: '#374151',
      // borderWidth:1,
      position: 'relative',
      height: '24%',
    },
    buttonRow: {
      flexDirection: 'row',
      transform: [{ translateX: '1.8%' }],
      marginHorizontal: 'auto',
      justifyContent: 'center',
      gap: '7%',
      height: '100%',
    },
    buttonHint: {
      color: isDark ? '#838A98' : '#5A5A5A',
      fontSize: 11,
      textAlign: 'center',
    },
    countText: {
      fontSize: 165,
      color: isDark ? '#FF9900' : '#FF9900',
      textAlign: 'center',
      fontWeight: '900',
      shadowOpacity: 1,
      shadowRadius: 10,
      shadowColor: 'grey',
      textShadowRadius: 20,
    },
    countTextView: {
      width: 100,
      height: 120,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'transparent',
      borderRadius: 12,
      overflow: 'hidden',
    },
    morphButton: {
      backgroundColor: '#e6ecf5',
      borderRadius: 20,
      shadowColor: '#fff',
      shadowOffset: { width: -6, height: -6 },
      shadowOpacity: 1,
      shadowRadius: 8,
      elevation: 8,
      borderWidth: 1,
      borderColor: '#f5f8fa',
      // Inner shadow simulation (Android workaround)
      overflow: 'visible',
    },
  });
};
