import { Dimensions } from 'react-native';

export const { height, width } = Dimensions.get('window');

// PERFORMANCE OPTIMIZED CONSTANTS for Extreme Performance
export const BUFFER_SIZE = 25; // Reduced from 40 for faster processing
// export const MIN_MOVEMENT_RANGE = 125; // Slightly reduced for faster detection
export const PATTERN_CONFIDENCE_THRESHOLD = 0.75; // Reduced for faster counting
export const ANALYSIS_INTERVAL = 20; // Increased frequency from 50ms to 30ms
export const MAX_FACE_GONE_TIME = 1500; // Reduced from 2000ms for faster reset
export const FLIP_DURATION = 300;

export const VOICES = Object.freeze({
  af_heart: {
    name: 'Heart',
    language: 'en-us',
    gender: 'Female',
    traits: '❤️',
    targetQuality: 'A',
    overallGrade: 'A',
  },
  af_alloy: {
    name: 'Alloy',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C',
  },
  af_aoede: {
    name: 'Aoede',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  af_bella: {
    name: 'Bella',
    language: 'en-us',
    gender: 'Female',
    traits: '🔥',
    targetQuality: 'A',
    overallGrade: 'A-',
  },
  af_jessica: {
    name: 'Jessica',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  af_kore: {
    name: 'Kore',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  af_nicole: {
    name: 'Nicole',
    language: 'en-us',
    gender: 'Female',
    traits: '🎧',
    targetQuality: 'B',
    overallGrade: 'B-',
  },
  af_nova: {
    name: 'Nova',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C',
  },
  af_river: {
    name: 'River',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  af_sarah: {
    name: 'Sarah',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  af_sky: {
    name: 'Sky',
    language: 'en-us',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C-',
  },
  am_adam: {
    name: 'Adam',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'D',
    overallGrade: 'F+',
  },
  am_echo: {
    name: 'Echo',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  am_eric: {
    name: 'Eric',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  am_fenrir: {
    name: 'Fenrir',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  am_liam: {
    name: 'Liam',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  am_michael: {
    name: 'Michael',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  am_onyx: {
    name: 'Onyx',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  am_puck: {
    name: 'Puck',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'B',
    overallGrade: 'C+',
  },
  am_santa: {
    name: 'Santa',
    language: 'en-us',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D-',
  },
  bf_emma: {
    name: 'Emma',
    language: 'en-gb',
    gender: 'Female',
    traits: '🚺',
    targetQuality: 'B',
    overallGrade: 'B-',
  },
  bf_isabella: {
    name: 'Isabella',
    language: 'en-gb',
    gender: 'Female',
    targetQuality: 'B',
    overallGrade: 'C',
  },
  bm_george: {
    name: 'George',
    language: 'en-gb',
    gender: 'Male',
    targetQuality: 'B',
    overallGrade: 'C',
  },
  bm_lewis: {
    name: 'Lewis',
    language: 'en-gb',
    gender: 'Male',
    targetQuality: 'C',
    overallGrade: 'D+',
  },
  bf_alice: {
    name: 'Alice',
    language: 'en-gb',
    gender: 'Female',
    traits: '🚺',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  bf_lily: {
    name: 'Lily',
    language: 'en-gb',
    gender: 'Female',
    traits: '🚺',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  bm_daniel: {
    name: 'Daniel',
    language: 'en-gb',
    gender: 'Male',
    traits: '🚹',
    targetQuality: 'C',
    overallGrade: 'D',
  },
  bm_fable: {
    name: 'Fable',
    language: 'en-gb',
    gender: 'Male',
    traits: '🚹',
    targetQuality: 'B',
    overallGrade: 'C',
  },
});

export const VOICE_DATA_URL =
  'https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/voices';

// Model options with their sizes and descriptions
const MODEL_BASE_URL =
  'https://huggingface.co/onnx-community/Kokoro-82M-ONNX/resolve/main/onnx';
export const MODELS = Object.freeze({
  'model.onnx': {
    name: 'Full Precision',
    size: '326 MB',
    description: 'Highest quality, largest size',
    url: `${MODEL_BASE_URL}/model.onnx`,
  },
  'model_fp16.onnx': {
    name: 'FP16',
    size: '163 MB',
    description: 'High quality, reduced size',
    url: `${MODEL_BASE_URL}/model_fp16.onnx`,
  },
  'model_q4.onnx': {
    name: 'Q4',
    size: '305 MB',
    description: 'Good quality, slightly reduced size',
    url: `${MODEL_BASE_URL}/model_q4.onnx`,
  },
  'model_q4f16.onnx': {
    name: 'Q4F16',
    size: '154 MB',
    description: 'Good quality, smaller size',
    url: `${MODEL_BASE_URL}/model_q4f16.onnx`,
  },
  'model_q8f16.onnx': {
    name: 'Q8F16',
    size: '86 MB',
    description: 'Balanced quality and size',
    url: `${MODEL_BASE_URL}/model_q8f16.onnx`,
  },
  'model_quantized.onnx': {
    name: 'Quantized',
    size: '92.4 MB',
    description: 'Reduced quality, smaller size',
    url: `${MODEL_BASE_URL}/model_quantized.onnx`,
  },
  'model_uint8.onnx': {
    name: 'UINT8',
    size: '177 MB',
    description: 'Lower quality, reduced size',
    url: `${MODEL_BASE_URL}/model_uint8.onnx`,
  },
  'model_uint8f16.onnx': {
    name: 'UINT8F16',
    size: '177 MB',
    description: 'Lower quality, reduced size',
    url: `${MODEL_BASE_URL}/model_uint8f16.onnx`,
  },
});

export const DEFAULT_VOICE_ID = 'am_onyx';
export const DEFAULT_MODEL = 'model.onnx';



export const motivationalMessages = [
  "First few down! You’re in the fight, stay hard!",
  "Keep grinding! You’re tougher than this!",
  "Pain is weakness leaving, keep pushing!",
  "Who’s gonna carry the boats? You are!",
  "Don’t stop, finish what you started!",
  "Embrace the suck, you’re built for this!",
  "Nobody saves you, push harder now!",
  "You’re not tired, you’re weak! Go on!",
  "Dig deep, you’ve got more in you!",
  "Suffering builds strength, own it!",
  "Quit whining, start winning! Push!",
  "You’re not done, keep hammering!",
  "Weakness hates effort, dominate it!",
  "Stay in the fight, you’re unbreakable!",
  "Pain is temporary, glory is forever! Push!",
  "No surrender, you’re tougher than this!",
  "Grind through, you’re a savage!",
  "Outwork your doubts, every rep counts!",
  "Stay hard, you’re forging a new you!",
  "Weakness runs from effort, chase it down!",
  "You’re built for battle, keep pushing!",
  "No limits, just effort! Get after it!",
  "Pain is your fuel, burn through it!",
  "Don’t quit, you’re stronger than you know!",
  "Stay savage, keep those reps coming!",
  "You’re not soft, prove it with every push!",
  "Grind now, shine later! Keep going!",
  "No excuses, you’re a beast, act like it!",
  "Push past the pain, that’s where growth lives!",
  "You’re not breaking, you’re building strength!",
  "Stay in the fight, you’re a warrior!",
  "Weakness fears you, show it no mercy!",
  "Every rep is a war won, keep fighting!",
  "Don’t stop, you’re tougher than this!",
  "Pain is your teacher, learn and push!",
  "You’re a savage, keep dominating those reps!",
  "No retreat, you’re stronger than your excuses!",
  "Stay hard, you’re carving out greatness!",
  "Push through the hurt, you’re unstoppable!",
  "Weakness can’t stand you, keep grinding!",
  "You’re a warrior, fight for every rep!",
  "No surrender, you’re built for this!",
  "Pain is just weakness exiting, push harder!",
  "Stay in the grind, you’re a beast!",
  "Don’t quit, you’re tougher than the toughest!",
  "Every rep builds your legacy, keep going!",
  "You’re not weak, prove it with every push!",
  "Stay savage, you’re dominating this!",
  "Grind through, you’re stronger than pain!",
  "No excuses, you’re a machine, keep going!",
  "Push past the hurt, you’re unstoppable!",
  "Weakness fears your effort, crush it!",
  "You’re a fighter, keep hammering those reps!",
  "Stay hard, you’re building something epic!",
  "Pain is your forge, craft a warrior!",
  "Don’t quit, you’re tougher than you know!",
  "Every rep is a war won, keep battling!",
  "You’re not soft, show it with every push!",
  "Stay in the grind, you’re a savage!",
  "No surrender, you’re stronger than steel!",
  "Push through the pain, you’re a legend!",
  "Weakness can’t touch you, keep working!",
  "You’re a warrior, own every single rep!",
  "Stay hard, you’re carving out greatness!",
  "Pain is your fuel, burn through it!",
  "Don’t stop, you’re a relentless force!",
  "Every rep builds your legacy, keep going!",
  "You’re not weak, prove it every push!",
  "Stay savage, you’re owning this fight!",
  "Grind through, you’re tougher than the toughest!",
  "No excuses, you’re a machine, act like it!",
  "Push harder, you’re forging a new you!",
  "Weakness flees from you, chase it down!",
  "You’re a fighter, keep hammering those reps!",
  "Stay hard, you’re building something epic!",
  "Pain is your forge, craft a legend!",
  "Don’t quit, you’re tougher than you know!",
  "Every rep is a victory, stack them up!",
  "You’re not soft, show it with every push!",
  "Stay savage, you’re dominating this fight!",
  "Grind through, you’re stronger than pain!",
  "No excuses, you’re a beast, keep going!",
  "Push past the hurt, you’re unstoppable!",
  "Weakness fears your effort, crush it!",
  "You’re a warrior, fight for every rep!",
  "Stay hard, you’re carving out greatness!",
  "Pain is your fuel, burn through it!",
  "Don’t stop, you’re a relentless machine!",
  "Every rep builds your legacy, keep fighting!",
  "You’re not weak, prove it every push!",
  "Stay savage, you’re owning this grind!",
  "Grind through, you’re tougher than the toughest!",
  "No excuses, you’re a machine, keep hammering!",
  "Push harder, you’re forging a legend!",
  "Weakness flees from you, chase it down!",
  "You’re a fighter, keep dominating those reps!",
  "Stay hard, you’re building an unbreakable you!",
  "Pain is your forge, craft a savage!",
  "Don’t quit, you’re the toughest out there!"
];

export const HapticFeedbackOptions = {
  enableVibrateFallback: true,
  ignoreAndroidSystemSettings: false,
};
