import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111827',
  },
  flex_1: {
    flex: 1,
  },
  canvas: {
    flex: 1,
    backgroundColor: '#E9EBED',
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  permissionBox: {
    backgroundColor: '#1F2937',
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#374151',
  },
  permissionLoader: {
    marginBottom: 20,
  },
  permissionTitle: {
    color: '#F9FAFB',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  permissionSubtitle: {
    color: '#9CA3AF',
    fontSize: 14,
    textAlign: 'center',
  },
  hiddenCamera: {
    position: 'absolute',
    opacity: 0,
    width: 1,
    height: 1,
  },
  headerContainer: {
    width: '95%',
    height: '7.5%',
    marginHorizontal: 'auto',
    marginTop: 16,
  },
  headerBox: {
    width: '100%',
    height: '100%',
    borderWidth: 1,
    flex: 1,
    borderColor: '#374151',
  },
  headerTitle: {
    color: '#F9FAFB',
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  stateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [
      {
        translateX: '-50%',
      },
      {
        translateY: '-50%',
      },
    ],
  },
  stateDot: {
    width: 12,
    height: 12,
    borderRadius: 12,
    marginRight: 8,
    boxShadow: [
      {
        offsetX: 0,
        offsetY: 0,
        blurRadius: 20,
        spreadDistance: 2,
        color: 'green',
      },
    ],
    elevation: 12,
  },
  stateText: {
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '500',
  },
  counterContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  counterBox: {
    backgroundColor: '#1F2937',
    borderRadius: 32,
    padding: 48,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#374151',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 10,
    minWidth: '70%',
    minHeight: '40%',
    alignContent: 'center',
    justifyContent: 'center',
  },
  counterLabel: {
    color: '#9CA3AF',
    fontSize: 18,
    fontWeight: '500',
    marginBottom: 12,
  },
  counterValue: {
    color: '#F9FAFB',
    fontSize: 80,
    fontWeight: '800',
    lineHeight: 80,
  },
  statusRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  buttonBoxContianer: {
    top: '50%',
    left: '50%',
    width: '100%',
    transform: [{ translateX: '-50%' }, { translateY: '-50%' }],
  },
  buttonBox: {
    // backgroundColor: '#1F2937',
    marginHorizontal: 'auto',
    marginBottom: 10,
    borderRadius: 20,
    transform: [
      {
        translateX: '1.2%',
      },
    ],
    width: '100%',
    padding: 2,
    // borderColor: '#374151',
    // borderWidth:1,
    position: 'relative',
    height: '24%',
  },
  buttonRow: {
    flexDirection: 'row',
    transform: [{ translateX: '1.8%' }],
    marginHorizontal: 'auto',
    justifyContent: 'center',
    gap: '4%',
    height: '100%',
  },
  buttonHint: {
    color: '#6B7280',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 8,
  },
  countText: {
    fontSize: 165,
    color: 'orange',
    textAlign: 'center',
    fontWeight: '900',
    shadowColor: 'white',
    shadowOffset: { height: 1, width: 1 },
    shadowOpacity: 1,
    shadowRadius: 20,
    textShadowColor: 'rgba(50,50,50,1)',
    textShadowOffset: { height: 3, width: 3 },
    textShadowRadius: 20,
  },
  countTextView: {
    width: 100,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderRadius: 12,
    overflow: 'hidden',
  },
  morphButton: {
    backgroundColor: '#e6ecf5',
    borderRadius: 20,
    shadowColor: '#fff',
    shadowOffset: { width: -6, height: -6 },
    shadowOpacity: 1,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#f5f8fa',
    // Inner shadow simulation (Android workaround)
    overflow: 'visible',
  },
});
